### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-2-evaluacion-intermedia-Mora-Porthe#1]
¿Hola @Mora-Porthe quieres terminar el ejercicio antes de que te lo corrija?

**Comment by Mora-Porthe** [comment]
Hola @migueldelmazo ! Claro, me pongo con ello en cuanto terminemos la lección de hoy. 
Ayer estuve recuperando lecciones atrasadas y no he visto los mensajes.  
Gracias!

**Comment by Mora-Porthe** [comment]
Listo @migueldelmazo !
#1

**Comment by migueldelmazo** [comment]
Hola @Mora-Porthe, muy buen curro, enhorabuena!!!

**Comment by Mora-Porthe** [comment]
Gracias @migueldelmazo, fue con ayuda del vídeo de Dayana donde explica el ejercicio, pero lo he entendido muy bien!
